child_001/urls.py
from django.urls import path
from .import views

app_name = 'child_001'

urlpatterns = [
    #path('', views.home, name='home'),
    path('', views.blog, name='blog'),
    path('blog/<int:id>/', views.readmore, name='readmore'),
    path('blog/cat/<int:id>/', views.cat, name='cat')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('child_001.urls')),
    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

child_001/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name = "Category Name")
    def __str__(self):
        return self.name

class Blog(models.Model):
    category_name = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.TextField()
    body = models.TextField()
    def __str__(self):
        return self.category_name.name
class test(models.Model):
    name = models.TextField()

# Logo
class Logo(models.Model):
    logo = models.ImageField(upload_to='logo/')
    

child_001/views.py
from django.shortcuts import render, HttpResponse
from . models import Blog, Category, Logo
# Create your views here.

# def home(request):
#     return render(request, 'blog/index.html')

def home(request):
    return render(request, 'blog/home-main.html')

def blog(request):
    data = Blog.objects.all().order_by('-id')
    logo = Logo.objects.all()
    context = {'dt': data, 'logo': logo}
    return render(request, 'blog/blog.html', context)

def readmore(request, id):
    data = Blog.objects.get(pk=id)
    logo = Logo.objects.all()
    print(data)
    context = {'rd': data, 'logo': logo}
    return render(request, 'blog/blog-read-more.html', context)   

def cat(request, id):
    data = Blog.objects.filter(category_name_id=id).order_by('-id')
    data2 = Blog.objects.all()
    logo = Logo.objects.all()
    print(data2)
    context = {'rd': data, 'dta': data2, 'logo': logo}
    return render(request, 'blog/categoryDetail.html', context)  

child_001/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    {% block link %}<link rel="stylesheet" href="{% static 'css/base.css' %}" /> {% endblock link %}
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

child_001/templates/blog/blog-read-more.html
{% extends 'blog/base.html' %}
{% load static %}
{% block link %}<link rel="stylesheet" href="{% static 'css/blog.css' %}" /> 
<link rel="stylesheet" href="{% static 'css/nav.css' %}" /> 
{% endblock link %}
{% block content %}
<div>
<img id='imglogo' src="{{ logo.logo.url }}" alt="" />
<!-- side by side content -->
</div>
{% include 'blog/navbar.html' %}
<div class="blog-width">
    <!-- <h2 class="">{{ rd.title|safe }}</h2> -->
    <p class="blog-p"><span class="blog-h1">{{ rd.title|safe }}</span><br>{{ rd.body|safe }}</p>
</div>
{% endblock %}

child_001/templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load static %}
{% block link %}<link rel="stylesheet" href="{% static 'css/blog.css' %}" /> {% endblock link %}
{% block content %}
{% include 'blog/navbar.html' %}
{% for data in dt %}
<div class="blog-width">
    <h1 class="blog-h1">{{ data.category_name }}</h1>
    <p class="blog-p">{{ data.title|safe }}</p>
    <button><a href="{% url 'child_001:readmore' data.id %}">Read more</a></button>
</div>
{% endfor %}
{% endblock %}

child_001/templates/blog/blogMenu.html
{% load static %}
{% block link %}<link rel="stylesheet" href="{% static 'css/blogMenu.css' %}" /> {% endblock link %}
<div class="fl">
    {% for data in dt %}
    {% ifchanged %}
    <a href="{% url 'child_001:cat' data.category_name_id %}"><li>{{ data.category_name }}</li></a>
    {% endifchanged %}
    
    {% endfor %}
</div>

child_001/templates/blog/categoryDetail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}" /> 
<link rel="stylesheet" href="{% static 'css/blogMenu.css' %}" /> 
<link rel="stylesheet" href="{% static 'css/nav.css' %}" /> 
{% endblock link %}
{% block content %}

<div>
    <img id='imglogo' src="{{ logo.logo.url }}" alt="" />
    <!-- side by side content -->
    </div>


{% include 'blog/navbar.html' %}

<div class="fl">
    {% for data in dta %}
    {% ifchanged %}
    <a href="{% url 'child_001:cat' data.category_name_id %}"><li>{{ data.category_name }}</li></a>
    {% endifchanged %}
    
    {% endfor %}
</div>

<hr class="blog-width">
{% for data in rd %}
<div class="blog-width">
    <h2 class="blog-h1">{{ data.title|safe }}</h2>
    <!-- <p class="blog-p">{{ data.title|safe }}</p> -->
    <button><a href="{% url 'child_001:readmore' data.id %}">Read more</a></button>
</div>
{% endfor %}


{% endblock %}

child_001/templates/blog/home-main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="text-align:center">Under Construction..</h1>
</body>
</html>

child_001/templates/blog/index.html
{% extends 'blog/base.html' %} 
{% block title %}AMRIT SHAHI {% endblock title %}
<br />
{% block content %} 
{% include 'blog/navbar.html' %} 
{% endblock content %}

child_001/templates/blog/navbar.html
{% load static %}
{% block link %}<link rel="stylesheet" href="{% static 'css/nav.css' %}" /> {% endblock link %}
<div>
  {% for logo in logo %}
<img id='imglogo' src="{{ logo.logo.url }}" alt="" />
{% endfor %}
<!-- side by side content -->
</div>

<!-- Second header -->
<div class="header">
  <div class="nav">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="#">Features</a></li>
      <li><a href="#">Portfolio</a></li>
      <li><a href="#">Resume</a></li>
      <li><a href="#">Testimonial</a></li>
      <li><a href="#">Clients</a></li>
      <li><a href="#">Pricing</a></li>
      <li><a href="/blog">Blog</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
</div>